version: '3.8'
services:
  web:
    build: ./
    ports:
      - "88:80"
    depends_on:
      - db
    expose:
      - 9010
    volumes:
      - ./:/var/www/html/
      - ./local/php.ini:/usr/local/etc/php/php.ini
      # - ./local/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


  db:
    image: 'mysql:8'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ChatSymf
    volumes:
      - ./var:/var/www/var
      - ./tools/docker/mysql:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMIN_DEFAULT_SERVER: db
      ADMIN_DESIGN: pepa-linha
    ports:
      - 8888:8080

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8000
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config

###< symfony/mercure-bundle ###


volumes:
  db-data:

  mercure_data:
  mercure_config:

    driver: local

networks:
  dev:
    driver: bridge
